### ISSUE TITLE
enable/disable multiple products at once

### ISSUE THREAD

**Issue by rjschwei** [SUSE/rmt#347] opened 2019-03-12 13:03 UTC
It should be possible to provide multiple product IDs to enable or disable for mirroring on the command line.

rmt-cli repos enable 1 2 3 4 5

should be supported.

**Comment by ikapelyukhin** [comment] 2019-03-14 16:38
@rjschwei That is supported, at least in the most recent version (implemented in #239 and #284). It is possible that it didn't get into the repos yet.

Closing. Also duplicate of #50.

**Closed by ikapelyukhin** 2019-03-14 16:38 UTC
